### PR TITLE
CMakeLists.txt

### PR DESCRIPTION
**Pull request by 3a4oT**
- modified CMakeLists.txt to allow generate the project with headers sources.

### CODE REVIEW

**Comment by 3a4oT** [comment]
@mulle-nat  For some reason, I can't assign reviewers.

**Comment by mulle-nat** [comment]
@3a4oT I don't know how the reviewer system works on github.

**Comment by 3a4oT** [comment]
@mulle-nat  there is a section for that in the right corner on each PR. Also, you can start review directly from ```Files changed``` tab and ask for changes if needed. Does ```release``` branch is the correct one to create PR or should it be ```master``` instead?
screen shot 2016-12-14 at 14 44 15

**Comment by mulle-nat** [comment]
Ugh right... I wasn't looking... This isn't the community repository.
The `mulle-nat` forks are release only.

**Comment by mulle-nat** [comment]
I reverted the pull request for now. I will merge in the changes from the community fork with the next release.

**Pull request merged**
